/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Two4design (https://sketchfab.com/two4design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-life-fellowship-terracotta-panel-2-eadf0d0512564a9b9b51d852308bbd09
Title: New Life Fellowship Terracotta Panel #2
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -5.083, -30]} rotation={[-Math.PI, 0, 0]}>
        <group position={[-19.003, -15.152, -1.409]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./scene.gltf')